# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Kaushik Asok
description: "Hi I'm Kaushik, and ğ‘€ğ‘ğ‘ ğ‘¡ğ‘’ğ‘Ÿ'ğ‘  ğ‘”ğ‘Ÿğ‘ğ‘‘ğ‘¢ğ‘ğ‘¡ğ‘’ ğ‘–ğ‘› ğµğ‘¢ğ‘ ğ‘–ğ‘›ğ‘’ğ‘ ğ‘  ğ´ğ‘›ğ‘ğ‘™ğ‘¦ğ‘¡ğ‘–ğ‘ğ‘  ğ‘“ğ‘Ÿğ‘œğ‘š ğ‘ğ‘ğ‘¡ğ‘–ğ‘œğ‘›ğ‘ğ‘™ ğ‘ˆğ‘›ğ‘–ğ‘£ğ‘’ğ‘Ÿğ‘ ğ‘–ğ‘¡ğ‘¦ ğ‘œğ‘“ ğ‘†ğ‘–ğ‘›ğ‘”ğ‘ğ‘ğ‘œğ‘Ÿğ‘’ (NUS) actively seeking full time opportunity as a Data Scientist.  My portfolio focuses on interesting projects I've recently undertaken, with a strong emphasis on business impact. Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "India/Singapore"
resume_url: /docs/KaushikA.pdf
avatar_image: /img/35482.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/kaushik-asok-002b19169/" # Add your linkedln handle
github: "https://github.com/kaushikkishen?tab=repositories"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

